#!/bin/bash

# Exit on error
set -e

#ubuntu 16.04
case "$1" in
    install)
    sudo useradd evision -s /bin/bash -m
	echo evision:evision | sudo chpasswd
	sudo usermod -aG sudo evision
	sudo grep -q -F 'evision ALL = NOPASSWD : ALL' /etc/sudoers || echo 'evision ALL = NOPASSWD : ALL' | sudo EDITOR='tee -a' visudo
	sudo su - evision << EOF
#Installing Node.JS
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
[ -s "/home/evision/.nvm/nvm.sh" ] && \. "/home/evision/.nvm/nvm.sh"
echo 'export NVM_DIR="/home/evision/.nvm"' >> ~/.profile
echo '[ -s "/home/evision/.nvm/nvm.sh" ] && \. "/home/evision/.nvm/nvm.sh"' >> ~/.profile
echo '[ -s "/home/evision/.nvm/bash_completion" ] && \. "/home/evision/.nvm/bash_completion"' >> ~/.profile
source ~/.profile
nvm install 8.12.0
nvm alias default v8.12.0
echo "nvm use default --silent" >> ~/.profile
npm i npm@latest -g

#Installing PM2
npm i pm2@latest -g
pm2 install pm2-logrotate

#Installing Node Modules
mkdir ~/evision
sudo chown evision:evision ~/evision/ -R
cd ~/evision
npm install body-parser@^1.18.2 cookie-parser@^1.4.3 cookie-session@^2.0.0-beta.3 enfsensure@^1.0.0 euclidean-distance@^1.0.0 express@4.10.1 express-session@^1.15.6 fast-csv@^2.4.1 file-stream-rotator@^0.2.0 find-remove@^1.2.0 fluent-ffmpeg@^2.1.2 get-port@^4.0.0 ip@^1.1.5 json-server@^0.12.1 jsonfile@^4.0.0 log-timestamp@^0.1.2 morgan@1.4.1 mqtt@^2.15.1 node-onvif@^0.1.2 node-uuid@^1.4.8 pm2@^3.0.3 request@^2.83.0 require-dir@^1.0.0 rotating-file-stream@^1.3.4 systeminformation@^3.42.9 ws@3.3.0
npm install git+https://github.com/nodeftpd/nodeftpd.git
npm install https://github.com/komunikator/mars.git

EOF
    ;;

	upgrade|abort-upgrade)
	sudo su - evision << EOF
#Starting
pm2 stop all
pm2 delete all
EOF
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac
